server:
  enable_http: true
  enable_ws: false
  enable_quic: false
  http_port: 8080
  ws_port: 9001
  quic_port: 4433
  cert_path: "./cert.pem"
  key_path: "./key.pem"


routes:
  - path: "/"
    upstream: "http://127.0.0.1:5000"
    cache: true
    plugins:
      - name: "hello"
        options: {}

  - path: "/api"
    upstream: "http://127.0.0.1:5001"
    cache: false
    plugins: []