server:
  http_port: 8080
  ws_port: 9001
  quic_port: 4433
  cert_path: "/Users/giorgiomartucci/rust_web/cert.pem"
  key_path: "/Users/giorgiomartucci/rust_web/key.pem"

routes:
  - path: "/"
    upstream: "http://127.0.0.1:5000"  
    cache: true
  - path: "/api"
    upstream: "http://127.0.0.1:5000" 
    cache: false

